#if defined _charger_const_included
    #endinput
#endif 

#define _charger_const_included

#define MAX_ENT             30
#define MENU_BLINK          0.1

/** 
 *  Charger animation sequences.
 */
#define CHARGER_SEQ_IDLE    0
#define CHARGER_SEQ_OFF     1

/** 
 *  Charger Bitflag sounds.
 */
#define CHARGER_SOUND_PLACED    (1 << 0)
#define CHARGER_SOUND_USING     (1 << 1)
#define CHARGER_SOUND_EMPTY     (1 << 2)




