#==============================================#
  # Charger by RedSMURF: Configuration file #
#==============================================#

# To add a new charger, follow the example below
# [Charger Name]
# CHARGER_MODEL           = Path of charger's model
# CHARGER_CLASS           = 0 - Health Charger,   1 - HEV Charger,      2 - CIV Charger
# CHARGER_MODE            = 0 - Restores Health,  1 - Restores Armor
# CHARGER_FLAGS           = a - Breaks,           b - Explodes
# CHARGER_SOUND           = 0 - Health Sound,     1 - HEV Sound
# CHARGER_SOUND_FLAGS     = a - Placed Sound,     b - Using Sound,      c - Empty Sound,      d - Refill Sound,     e - Removed Sound
# CHARGER_RATE            = Amount of Health/Armor given per use
# CHARGER_COOLDOWN        = Delay in seconds between each use
# CHARGER_CAPACITY        = Maximum amount of Health/Armor this charger can give
# CHARGER_LIMIT           = Prevents if the player exceeds the charger's unit limit, -1 - No Limit
# CHARGER_REFILL          = Delay in seconds for the charger to refill, -1 - Disabled
# CHARGER_DELAY           = Seconds before the charger get activated
# CHARGER_HEALTH          = Charger's health (Default = 250)
# CHARGER_BREAK_RATIO     = Overload added to each use
# CHARGER_BREAK_THRESHOLD = Overload limit before break check
# CHARGER_BREAK_CHANCE    = Probability to break once threshold reached
# CHARGER_EXPLODE_DAMAGE  = Explosion Damage (Default = 100)
# CHARGER_EXPLODE_RADIUS  = Explosion Radius (Default = 150)

# To make a charger available in the menu, you must defined at least it's name like this [Health Charger]
# Charger model and sound cannot be changed dynamically during gameplay

[Main Settings]
SETTING_DEFAULT_MODEL           = models/Charger/healthcharger.mdl

SETTING_SOUND_HEALTH_PLACE      = items/medshot4.wav
SETTING_SOUND_HEALTH_USE        = items/medcharge4.wav
SETTING_SOUND_HEALTH_EMPTY      = items/medshotno1.wav
SETTING_SOUND_HEALTH_REMOVE     = items/medshotno1.wav
SETTING_SOUND_HEALTH_REFILL     = items/medshot4.wav
SETTING_SOUND_HEV_PLACE         = items/suitchargeok1.wav
SETTING_SOUND_HEV_USE           = items/suitcharge1.wav
SETTING_SOUND_HEV_EMPTY         = items/suitchargeno1.wav
SETTING_SOUND_HEV_REMOVE        = items/suitchargeno1.wav
SETTING_SOUND_HEV_REFILL        = items/suitchargeok1.wav
SETTING_SOUND_FLICKER           = debris/zap1.wav
SETTING_SOUND_FLICKER           = buttons/spark1.wav
SETTING_SOUND_FLICKER           = buttons/spark6.wav

SETTING_MINS_STANDARD           = -6.5 -13.25 -25.0
SETTING_MAXS_STANDARD           = 6.5 13.25 25.0
SETTING_MINS_CIVILIAN           = -3.5 -12.25 -24.0
SETTING_MAXS_CIVILIAN           = 3.5 12.25 24.0

SETTING_CHARGER_LOAD            = 1       # Whether to load saved charger data of the current map
SETTING_CHARGER_RANGE           = 75.0    # Max distance to interact with a charger
SETTING_OFFSET_BASE             = 90.0    # Default forward offset when previewing charger placement
SETTING_OFFSET_MIN              = 42.0    # Minimum offset from the player to the charger
SETTING_OFFSET_MAX              = 900.0   # Maximum offset from the player to the charger
SETTING_OFFSET_STEP             = 10.0    # Step size when scrolling to move charger forward/backward
SETTING_OFFSET_FREQ             = 0.1     # Scroll responsivness for placement offset (lower = faster)
SETTING_GHOST_FREQ              = 0.1     # Refresh rate of the ghost model (min = 0.1)
SETTING_GHOST_ALPHA             = 90      # Transparency level of the ghost preview model (0 - 255)

[Health Charger 25]
CHARGER_MODEL             = models/Charger/healthcharger.mdl
CHARGER_CLASS             = 0
CHARGER_MODE              = 0
CHARGER_SOUND             = 0
CHARGER_SOUND_FLAGS       = abcde
CHARGER_RATE              = 1.0
CHARGER_COOLDOWN          = 0.1
CHARGER_CAPACITY          = 25.0
CHARGER_LIMIT             = 200.0
CHARGER_REFILL            = 5.0

[Health Charger 25 (Double)]
CHARGER_MODEL             = models/Charger/healthcharger.mdl
CHARGER_CLASS             = 0
CHARGER_MODE              = 0
CHARGER_SOUND             = 0
CHARGER_SOUND_FLAGS       = abcde
CHARGER_RATE              = 2.0
CHARGER_COOLDOWN          = 0.1
CHARGER_CAPACITY          = 25.0
CHARGER_LIMIT             = 200.0
CHARGER_REFILL            = 5.0

[Health Charger 25 (Takes Damage)]
CHARGER_MODEL             = models/Charger/healthcharger.mdl
CHARGER_CLASS             = 0
CHARGER_MODE              = 0
CHARGER_FLAGS             = a
CHARGER_SOUND             = 0
CHARGER_SOUND_FLAGS       = abcde
CHARGER_RATE              = 1.0
CHARGER_COOLDOWN          = 0.1
CHARGER_CAPACITY          = 25.0
CHARGER_LIMIT             = 200.0
CHARGER_REFILL            = 5.0
CHARGER_HEALTH            = 250.0

[Health Charger 25 (EXPLODES)]
CHARGER_MODEL             = models/Charger/healthcharger.mdl
CHARGER_CLASS             = 0
CHARGER_MODE              = 0
CHARGER_FLAGS             = ab
CHARGER_SOUND             = 0
CHARGER_SOUND_FLAGS       = abcde
CHARGER_RATE              = 1.0
CHARGER_COOLDOWN          = 0.1
CHARGER_CAPACITY          = 25.0
CHARGER_LIMIT             = 200.0
CHARGER_REFILL            = 5.0
CHARGER_DELAY             = 5.0
CHARGER_HEALTH            = 250.0
CHARGER_BREAK_RATIO       = 25.0
CHARGER_BREAK_THRESHOLD   = 70.0
CHARGER_BREAK_CHANCE      = 0.9
CHARGER_EXPLODE_DAMAGE    = 100.0
CHARGER_EXPLODE_RADIUS    = 150.0

[Health Charger 50]
CHARGER_MODEL             = models/Charger/healthcharger.mdl
CHARGER_CLASS             = 0
CHARGER_MODE              = 0
CHARGER_SOUND             = 0
CHARGER_SOUND_FLAGS       = abcde
CHARGER_RATE              = 1.0
CHARGER_COOLDOWN          = 0.1
CHARGER_CAPACITY          = 50.0
CHARGER_LIMIT             = 200.0
CHARGER_REFILL            = 30.0

[HEV Charger 25]
CHARGER_MODEL             = models/Charger/hevcharger.mdl
CHARGER_CLASS             = 1
CHARGER_MODE              = 1
CHARGER_SOUND             = 1
CHARGER_SOUND_FLAGS       = abcde
CHARGER_RATE              = 1.0
CHARGER_COOLDOWN          = 0.1
CHARGER_CAPACITY          = 25.0
CHARGER_LIMIT             = 200.0
CHARGER_REFILL            = 5.0

[CIV Charger 10]
CHARGER_MODEL             = models/Charger/civ_charger.mdl
CHARGER_CLASS             = 2
CHARGER_MODE              = 1
CHARGER_SOUND             = 1
CHARGER_SOUND_FLAGS       = abcde
CHARGER_RATE              = 1.0
CHARGER_COOLDOWN          = 0.2
CHARGER_CAPACITY          = 10.0
CHARGER_LIMIT             = 200.0
CHARGER_REFILL            = 1.0

[SUPER IDOL (No Limit)]
CHARGER_MODEL             = models/Charger/healthcharger.mdl
CHARGER_CLASS             = 0
CHARGER_MODE              = 0
CHARGER_SOUND             = 0
CHARGER_SOUND_FLAGS       = abcde
CHARGER_RATE              = 20.0
CHARGER_COOLDOWN          = 0.1
CHARGER_CAPACITY          = 2500.0
CHARGER_LIMIT             = -1
CHARGER_REFILL            = 10.0