#==============================================#
  # Charger by RedSMURF: Configuration file #
#==============================================#

# To add a new charger, follow the example below
# [Charger Name]
# CHARGER_MODEL           = Path of charger's model.
# CHARGER_CLASS           = 0 - Health Charger,   1 - HEV Charger,   2 - CIV charger.
# CHARGER_MODE            = 0 - Restores Health,  1 - Restores Armor.
# CHARGER_SOUND           = 0 - Health Sound,     1 - HEV Sound
# CHARGER_SOUND_FLAGS     = a - Placed Sound,     b - Using Sound, c - Empty Sound (BitFlags)
# CHARGER_RATE            = Amount of Health/Armor given per use.
# CHARGER_COOLDOWN        = Delay in seconds between each use.
# CHARGER_CAPACITY        = Maximum amount of Health/Armor this charger can give.
# CHARGER_LIMIT           = Prevents if the player exceeds the charger's unit limit.
# CHARGER_REFILL          = Delay in seconds for the charger to refill, -1 - disable

# To make a charger available in the menu, you must defined at least it's name like this [Health Charger].
# Charger model and sound cannot be changed dynamically during gameplay.

[Main Settings]
SETTING_DEFAULT_MODEL     = models/Charger/healthcharger.mdl
SETTING_DEFAULT_RATE      = 1.0
SETTING_DEFAULT_COOLDOWN  = 0.2
SETTING_DEFAULT_CAPACITY  = 100.0
SETTING_DEFAULT_LIMIT     = 150.0

SETTING_HEALTH_PLACED     = items/medshot4.wav
SETTING_HEALTH_USING      = items/medcharge4.wav
SETTING_HEALTH_EMPTY      = items/medshotno1.wav
SETTING_HEV_PLACED        = items/suitchargeok1.wav
SETTING_HEV_USING         = items/suitcharge1.wav
SETTING_HEV_EMPTY         = items/suitchargeno1.wav
SETTING_MINS_STANDARD     = -6.2 -6.2 -25.0
SETTING_MAXS_STANDARD     = 6.2 6.2 22.0
SETTING_MINS_CIVILIAN     = -4.7 -4.7 -22.0
SETTING_MAXS_CIVILIAN     = 4.7 4.7 22.0

SETTING_CHARGER_LOAD      = 1       # Whether to load saved charger data of the current map
SETTING_CHARGER_RANGE     = 65.0    # Max distance to interact with a charger.
SETTING_OFFSET_BASE       = 90.0    # Default forward offset when previewing charger placement
SETTING_OFFSET_MIN        = 42.0    # Minimum offset from the player to the charger
SETTING_OFFSET_MAX        = 250.0   # Maximum offset from the player to the charger
SETTING_OFFSET_STEP       = 10.0    # Step size when scrolling to move charger forward/backward
SETTING_OFFSET_FREQ       = 0.1     # Scroll responsivness for placement offset ( lower = faster )
SETTING_GHOST_ALPHA       = 90      # Transparency level of the ghost preview model ( 0 - 255 )
SETTING_GHOST_FREQ        = 0.1     # Refresh rate of the ghost model ( min = 0.1 )

[Health Charger 25]
CHARGER_MODEL             = models/Charger/healthcharger.mdl
CHARGER_CLASS             = 0
CHARGER_MODE              = 0
CHARGER_SOUND             = 0
CHARGER_SOUND_FLAGS       = abc
CHARGER_RATE              = 1.0
CHARGER_COOLDOWN          = 0.1
CHARGER_CAPACITY          = 25.0
CHARGER_LIMIT             = 200.0
CHARGER_REFILL            = 5.0

[Health Charger Double 25]
CHARGER_MODEL             = models/Charger/healthcharger.mdl
CHARGER_CLASS             = 0
CHARGER_MODE              = 0
CHARGER_SOUND             = 0
CHARGER_SOUND_FLAGS       = abc
CHARGER_RATE              = 2.0
CHARGER_COOLDOWN          = 0.1
CHARGER_CAPACITY          = 25.0
CHARGER_LIMIT             = 200.0
CHARGER_REFILL            = 3.0

[Health Charger 50]
CHARGER_MODEL             = models/Charger/healthcharger.mdl
CHARGER_CLASS             = 0
CHARGER_MODE              = 0
CHARGER_SOUND             = 0
CHARGER_SOUND_FLAGS       = abc
CHARGER_RATE              = 1.0
CHARGER_COOLDOWN          = 0.1
CHARGER_CAPACITY          = 50.0
CHARGER_LIMIT             = 200.0
CHARGER_REFILL            = 30.0

[HEV Charger 25]
CHARGER_MODEL             = models/Charger/hevcharger.mdl
CHARGER_CLASS             = 1
CHARGER_MODE              = 1
CHARGER_SOUND             = 1
CHARGER_SOUND_FLAGS       = abc
CHARGER_RATE              = 1.0
CHARGER_COOLDOWN          = 0.1
CHARGER_CAPACITY          = 25.0
CHARGER_LIMIT             = 200.0

[CIV Charger 10]
CHARGER_MODEL             = models/Charger/civ_charger.mdl
CHARGER_CLASS             = 2
CHARGER_MODE              = 1
CHARGER_SOUND             = 1
CHARGER_SOUND_FLAGS       = abc
CHARGER_RATE              = 1.0
CHARGER_COOLDOWN          = 0.2
CHARGER_CAPACITY          = 10.0
CHARGER_LIMIT             = 200.0
CHARGER_REFILL            = 1.0