#==============================================#
  # Charger by RedSMURF: Configuration file #
#==============================================#

# To add a new charger, follow the example below
# [Charger Name]
# CHARGER_MODEL              = Path to the charger's model
# CHARGER_CLASS              = 0 - Health Charger     1 - HEV Charger        2 - CIV Charger
# CHARGER_FLAGS              = a - Breakable          b - Explosive          c - Wear                  d - Spark               e - Sound            f - Gib
# CHARGER_TEAM               = 0 - None               1 - Terrorist          2 - Counter-Terrorist     3 - Both
# CHARGER_SOUND              = 0 - Health Sound       1 - HEV Sound
# CHARGER_MODE               = 0 - Health Mode        1 - Armor Mode
# CHARGER_RATE               = Amount of Health/Armor given per use
# CHARGER_DELAY              = Delay in seconds between each use
# CHARGER_CAPACITY           = Initial amount of Health/Armor available
# CHARGER_CAPACITY_MAX       = Maximum capacity the charger can hold
# CHARGER_LIMIT              = Player usage limit
# CHARGER_REFILL             = Refill delay in seconds
# CHARGER_DELAY_ACTIVE       = Delay in seconds before the charger becomes active at round start
# CHARGER_SPAWN_MODE         = 0 - Never              1 - Delayed            2 - Round Start
# CHARGER_SPAWN              = Minimum - Maximum spawn time
# CHARGER_SPAWN_CHANCE       = Chance to spawn (0.0 - 1.0)
# CHARGER_HEALTH             = Charger health (Default = 250)
# CHARGER_OVERLOAD           = Current overload value
# CHARGER_BREAK_RATIO        = Overload added per use
# CHARGER_BREAK_THRESHOLD    = Overload value required before break check
# CHARGER_BREAK_CHANCE       = Chance to break once threshold is reached
# CHARGER_EXPLODE_DAMAGE     = Explosion damage (Default = 100)
# CHARGER_EXPLODE_RADIUS     = Explosion radius (Default = 150)

# To make a charger available in the menu, you must defined at least it's name like this [Health Charger]
# Charger model and sound cannot be changed dynamically during gameplay

[Main Settings]
SETTING_DEFAULT_MODEL           = models/Charger/health.mdl
SETTING_DEFAULT_GIB             = models/computergibs.mdl
SETTING_DEFAULT_CLASS           = 0
SETTING_DEFAULT_FLAGS           = adef
SETTING_DEFAULT_TEAM            = 3
SETTING_DEFAULT_SOUND           = 0
SETTING_DEFAULT_MODE            = 0

SETTING_DEFAULT_SPAWN_MODE      = 1
SETTING_DEFAULT_SPAWN           = 10.0 25.0
SETTING_DEFAULT_SPAWN_CHANCE    = 1.0

SETTING_DEFAULT_RATE            = 1.0
SETTING_DEFAULT_DELAY           = 0.1
SETTING_DEFAULT_CAPACITY        = 100.0
SETTING_DEFAULT_CAPACITY_MAX    = 100.0
SETTING_DEFAULT_LIMIT           = 0.0
SETTING_DEFAULT_REFILL          = 0.0
SETTING_DEFAULT_DELAY_ACTIVE    = 0.0

SETTING_DEFAULT_HEALTH          = 125.0
SETTING_DEFAULT_EXPLODE_DAMAGE  = 100.0
SETTING_DEFAULT_EXPLODE_RADIUS  = 150.0
SETTING_DEFAULT_BREAK_RATIO     = 7.5
SETTING_DEFAULT_BREAK_THRESHOLD = 70.0
SETTING_DEFAULT_BREAK_CHANCE    = 0.4

SETTING_MINS_STANDARD           = -7.75 -16.0 -24.0
SETTING_MAXS_STANDARD           = 7.75 16.0 24.0
SETTING_MINS_CIVILIAN           = -3.5 -12.0 -24.0
SETTING_MAXS_CIVILIAN           = 4 12.0 24.0

SETTING_CHARGER_LOAD            = 1           # Whether to load saved charger data of the current map
SETTING_CHARGER_ACTION          = 1           # Whether chargers can be placed
SETTING_CHARGER_RANGE           = 75.0        # Max distance to interact with a charger
SETTING_OFFSET_BASE             = 90.0        # Default forward offset when previewing charger placement
SETTING_OFFSET                  = 42.0 900.0  # Minimum offset from the player to the charger
SETTING_OFFSET_STEP             = 10.0        # Step size when scrolling to move charger forward/backward
SETTING_OFFSET_FREQ             = 0.1         # Scroll responsivness for placement offset (lower = faster)
SETTING_GHOST_FREQ              = 0.1         # Refresh rate of the ghost model (min = 0.1)
SETTING_GHOST_ALPHA             = 90          # Transparency level of the ghost preview model (0 - 255)

SETTING_BREAK_VELO_Z            = 7.0 12.0
SETTING_BREAK_VELO_RANDOM       = 7 12
SETTING_BREAK_COUNT             = 4 7
SETTING_BREAK_LIFE              = 10 15

SETTING_SPRITE_ZEROGXPLODE      = sprites/zerogxplode.spr
SETTING_SOUND_MENU_NAV          = buttons/blip1.wav
SETTING_SOUND_MENU_REMOVE       = buttons/button10.wav
SETTING_SOUND_MENU_ALERT        = buttons/bell1.wav

SETTING_SOUND_HEALTH_SHOT       = items/medshot4.wav
SETTING_SOUND_HEALTH_NO         = items/medshotno1.wav
SETTING_SOUND_HEALTH_CHARGE     = items/medcharge4.wav
SETTING_SOUND_HEV_SHOT          = items/suitchargeok1.wav
SETTING_SOUND_HEV_NO            = items/suitchargeno1.wav
SETTING_SOUND_HEV_CHARGE        = items/suitcharge1.wav
SETTING_SOUND_FLICKER           = debris/zap1.wav
SETTING_SOUND_FLICKER           = buttons/spark1.wav
SETTING_SOUND_FLICKER           = buttons/spark6.wav
SETTING_SOUND_METAL             = debris/bustmetal1.wav
SETTING_SOUND_METAL             = debris/bustmetal2.wav

SETTING_COLOR_ACTIVE            = 0 255 0
SETTING_COLOR_INACTIVE          = 255 0 0

[Health Default]
CHARGER_CLASS           = 0
CHARGER_MODEL           = models/Charger/health.mdl
CHARGER_MODE            = 0
CHARGER_SOUND           = 0
CHARGER_RATE            = 1.0
CHARGER_CAPACITY        = 25.0

[Health Fast]
CHARGER_CLASS           = 0
CHARGER_MODEL           = models/Charger/health.mdl
CHARGER_MODE            = 0
CHARGER_SOUND           = 0
CHARGER_RATE            = 5.0
CHARGER_CAPACITY        = 75.0

[Health Limited]
CHARGER_CLASS           = 0
CHARGER_MODEL           = models/Charger/health.mdl
CHARGER_MODE            = 0
CHARGER_SOUND           = 0
CHARGER_LIMIT           = 50.0
CHARGER_CAPACITY        = 50.0

[Health SUPER IDOL]
CHARGER_CLASS           = 0
CHARGER_MODEL           = models/Charger/health.mdl
CHARGER_MODE            = 0
CHARGER_SOUND           = 0
CHARGER_RATE            = 25.0
CHARGER_CAPACITY        = 1000.0

[HEV Breakable]
CHARGER_CLASS           = 1
CHARGER_MODEL           = models/Charger/hev.mdl
CHARGER_MODE            = 1
CHARGER_SOUND           = 1
CHARGER_FLAGS           = adef
CHARGER_BREAK_RATIO     = 5.0
CHARGER_BREAK_THRESHOLD = 40.0
CHARGER_BREAK_CHANCE    = 0.4

[HEV Breakable Flesh]
CHARGER_CLASS           = 1
CHARGER_MODEL           = models/Charger/hev.mdl
CHARGER_MODE            = 1
CHARGER_SOUND           = 1
CHARGER_FLAGS           = adef
CHARGER_BREAK_RATIO     = 5.0
CHARGER_BREAK_THRESHOLD = 40.0
CHARGER_BREAK_CHANCE    = 0.4
CHARGER_BREAK_FLAG      = 4
CHARGER_GIB             = 7
CHARGER_BUST_SOUND      = 16

[HEV Explosive Metal]
CHARGER_CLASS           = 1
CHARGER_MODEL           = models/Charger/hev.mdl
CHARGER_MODE            = 1
CHARGER_SOUND           = 1
CHARGER_FLAGS           = abdef
CHARGER_EXPLODE_DAMAGE  = 120.0
CHARGER_EXPLODE_RADIUS  = 180.0

[HEV CT Only]
CHARGER_CLASS           = 1
CHARGER_MODEL           = models/Charger/hev.mdl
CHARGER_MODE            = 1
CHARGER_SOUND           = 1
CHARGER_TEAM            = 2

[HEV High Capacity]
CHARGER_CLASS           = 1
CHARGER_MODEL           = models/Charger/hev.mdl
CHARGER_MODE            = 1
CHARGER_SOUND           = 1
CHARGER_RATE            = 2
CHARGER_CAPACITY        = 200.0

[HEV Explosive Bones]
CHARGER_CLASS           = 1
CHARGER_MODEL           = models/Charger/hev.mdl
CHARGER_MODE            = 1
CHARGER_SOUND           = 1
CHARGER_FLAGS           = abdef
CHARGER_BREAK_FLAG      = 4
CHARGER_GIB             = 2
CHARGER_BUST_SOUND      = 16

[HEV Active Delayed]
CHARGER_CLASS           = 1
CHARGER_MODEL           = models/Charger/hev.mdl
CHARGER_MODE            = 1
CHARGER_SOUND           = 1
CHARGER_DELAY_ACTIVE    = 20.0

[HEV Short Respawn]
CHARGER_CLASS           = 1
CHARGER_MODEL           = models/Charger/hev.mdl
CHARGER_MODE            = 1
CHARGER_SOUND           = 1
CHARGER_FLAGS           = abdef
CHARGER_RATE            = 1.0
CHARGER_SPAWN_MODE      = 1
CHARGER_SPAWN           = 2.0 5.0

[CIV Default]
CHARGER_CLASS           = 2
CHARGER_MODEL           = models/Charger/civ.mdl
CHARGER_MODE            = 1
CHARGER_SOUND           = 1
CHARGER_RATE            = 2.0
CHARGER_CAPACITY        = 50.0

[CIV High HP]
CHARGER_CLASS           = 2
CHARGER_MODEL           = models/Charger/civ.mdl
CHARGER_MODE            = 1
CHARGER_SOUND           = 1
CHARGER_FLAGS           = adef
CHARGER_BREAK_FLAG      = 2
CHARGER_GIB             = 10
CHARGER_BUST_SOUND      = 18
CHARGER_HEALTH          = 500.0

[CIV Glass]
CHARGER_CLASS           = 2
CHARGER_MODEL           = models/Charger/civ.mdl
CHARGER_MODE            = 1
CHARGER_SOUND           = 1
CHARGER_FLAGS           = adef
CHARGER_BREAK_FLAG      = 1
CHARGER_GIB             = 9
CHARGER_BUST_SOUND      = 17

[CIV Random Spawn]
CHARGER_CLASS           = 2
CHARGER_MODEL           = models/Charger/civ.mdl
CHARGER_MODE            = 1
CHARGER_SOUND           = 1
CHARGER_SPAWN_MODE      = 0
CHARGER_SPAWN_CHANCE    = 0.5



